version: '3.3'
services:
  db:
    container_name: 'wordpress_next-db'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    networks:
      net:
  wordpress:
    container_name: 'wordpress_next'
    depends_on:
      - db
    image: 'wordpress:5.9'
    ports:
      - '5000:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    networks:
      net:
    volumes:
      - "./wordpress:/var/www/html"
      - "./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins"
#  filewatcher:
#    container_name: watcher
#    build:
#      context: wordpress/wp-content/themes/BestMegaReels/Filewatcher/
#    volumes:
#      - "./wordpress/wp-content/themes/BestMegaReels/:/usr/app/Server/"
  adminDb:
    image: phpmyadmin:latest
    container_name: 'wordpress_next-db-admin'
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PASSWORD: somewordpress
      PMA_USER: someuser
    networks:
      net:
  frontend:
    build: nextjs
    container_name: "nextjs_front"
    depends_on:
      - "wordpress"
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs/my-app:/usr/app/nextjs
    networks:
      net:

networks:
  net: